version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:1337
    volumes:
      - ./:/usr/src/app/
    ports:
      - 1337:1337
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=sqs://
      - CELERY_BACKEND=sqs://
    

  celery:
    build: ./
    command: celery --app=LabelWebApp.celery worker --loglevel=info --concurrency 4
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=sqs://
      - CELERY_BACKEND=sqs://
    depends_on:
      - web
       
      
  celery-beat:
    build: ./
    command: celery --app=LabelWebApp.celery beat --loglevel=info
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=sqs://
      - CELERY_BACKEND=sqs://
    depends_on:
      - web
       
  dashboard:
    build: ./
    command: celery flower -A core --port=5555 --broker=sqs://
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=sqs://
      - CELERY_BACKEND=sqs://
    depends_on:
      - web
      - celery

